### ISSUE TITLE
"Main" branches is not actively

### ISSUE THREAD

**Issue by baboon-king** [xiaoxunyao/cn.vitest.dev#157]
![image](https://user-images.githubusercontent.com/63645337/197668999-9f3e7bed-ebcb-4d19-94d1-c833d9d96b36.png)

现在默认的和活跃的分支是 `dev`，或许可以修改下 [Wike](https://github.com/vitest-dev/docs-cn/wiki/%E5%90%88%E4%BD%9C%E8%A7%84%E8%8C%83#%E8%B4%A1%E7%8C%AE%E6%96%B9%E5%BC%8F)

**Comment by elonehoo** [comment]
忘了，不好意思

**Comment by baboon-king** [comment]
> 忘了，不好意思

没事，不影响。
只是有歧义，感觉怪怪的！
