### ISSUE TITLE
Add search feature

### ISSUE THREAD

**Issue by Alkaidcc** [xiaoxunyao/cn.vitest.dev#164]
I wish [vitest-cn](https://cn.vitest.dev/) add search feature just like [vite-cn](https://cn.vitejs.dev/)

**Comment by daiwanxing** [comment]
@elonehoo  请问搜索功能啥时候能支持

**Comment by elonehoo** [comment]
啊，还没成功吗，我看一下

**Comment by elonehoo** [comment]
不好意思不好意思

**Comment by daiwanxing** [comment]
> 不好意思不好意思

看了下 `config.js` 中 `algolia` 这个配置项是已经配置好了的，但是不知道为什么被注释掉了🤣

**Comment by elonehoo** [comment]
不好意思，我设置一下，那个是 antfu 的，我的好像被替换掉了，实在是不好意思，我以为有了，只是 vitepress 没显示

**Comment by watonyweng** [comment]
貌似搜索不到结果

![abc](https://user-images.githubusercontent.com/2574065/225260514-0d057648-1a69-4002-aa81-012fbb4880e2.jpg)

**Comment by elonehoo** [comment]
🤔，我去看看接口是不是失败了

**Comment by elonehoo** [comment]
坏

**Comment by watonyweng** [comment]
Hi @elonehoo @daiwanxing, can you search results by algolia?

**Comment by elonehoo** [comment]
我也不行，但是我的algolia告诉我成功了

**Comment by elonehoo** [comment]
我在想怎么办

**Comment by daiwanxing** [comment]
我记得 algolia 需要大约一天的时间爬取整个网站的内容

**Comment by watonyweng** [comment]
Hi @elonehoo @daiwanxing, we can use [action](https://github.com/algolia/algoliasearch-crawler-github-actions) to build and crawle index for algolia.

**Comment by daiwanxing** [comment]
这个 action 不错

**Comment by elonehoo** [comment]
那就试试看

**Comment by Alkaidcc** [comment]
Has the search feature been available? If not, you can try to use https://github.com/emersonbottero/vitepress-plugin-search to implement it.

**Comment by Alkaidcc** [comment]
Hi, @elonehoo https://cn.vitest.dev/ still not working, can you check it? 
![image](https://user-images.githubusercontent.com/54631354/235919627-39654ec0-2cad-4424-9302-eed77190ea02.png)

**Comment by elonehoo** [comment]
我看一下，我刚才测试的时候没问题

**Comment by elonehoo** [comment]
@Alkaidcc 应该好了

**Comment by elonehoo** [comment]
麻烦再试一下？或者刷新一下
<img width="1710" alt="image" src="https://user-images.githubusercontent.com/43719490/235920837-097e6883-2ee0-4428-8796-f46e5932114f.png">

**Comment by elonehoo** [comment]
泰裤辣

**Comment by Alkaidcc** [comment]
everything works well, Thanks!
