### ISSUE TITLE
刷新页面或直接通过 URL 访问文档页面无内容

### ISSUE THREAD

**Issue by KiritaniAyaka** [xiaoxunyao/cn.vitest.dev#199]
浏览过程中刷新页面会导致文档内容为空，直接通过 URL 访问文档页面也会触发，英文站点无此问题

刷新页面的演示：

![cn_site](https://user-images.githubusercontent.com/26200808/214320635-872385bb-6990-44ed-928c-549aa15eb094.gif)

英文站点表现正常：

![en_site](https://user-images.githubusercontent.com/26200808/214320673-f6914553-161a-4fbb-bab4-c64682f37f94.gif)

直接通过 URL 打开的演示：

![open_with_url](https://user-images.githubusercontent.com/26200808/214320732-b5fa3860-50d4-4880-90b0-5f30e42b5db7.gif)

使用的浏览器是 Chrome 109.0.5414.75，在新版 Edge 和 Android 上的 Via 浏览器上也能 100% 复现，所有 Chromium 系浏览器可能都可以复现

---

个人一点不成熟的猜测：可能是 workbox 的缓存导致

**Comment by watonyweng** [comment]
Hi @KiritaniAyaka, thank you for your feedback and welcome to contribute.

**Comment by KiritaniAyaka** [comment]
在[最近的更新](https://github.com/vitest-dev/docs-cn/commit/aab536d4022339e70ad9dbdf81754e57c0f08e89)后有一个新的发现：

访问过英文站点的浏览器在中文站点无法复现此问题，而从未访问过英文站点的浏览器仍然可以复现，之前并不是这样。希望对 debug 有帮助。

**Comment by watonyweng** [comment]
Hi @KiritaniAyaka, could you please help me to see if this issue can be reproduced? please click [here](https://github.com/vitest-dev/docs-cn/commit/55d8b86bd7a4519da0c80695b3985bd3eb86893d) for more information.
