### ISSUE TITLE
a merge conflict come out in the example code 

### ISSUE THREAD

**Issue by Nauxscript** [xiaoxunyao/cn.vitest.dev#225]
位于 [vi-domock)](https://cn.vitest.dev/api/#vi-domock) 

![image](https://user-images.githubusercontent.com/13010589/222615939-e9dcd65f-06cb-45ea-aa14-3b6c51a523ad.png)

在代码中发现该问题已经修复，但线上环境并没有正确显示

**Comment by elonehoo** [comment]
具体在哪里啊

**Comment by elonehoo** [comment]
给个线上的链接

**Comment by Nauxscript** [comment]
已更新链接

**Comment by elonehoo** [comment]
好了
