### ISSUE TITLE
sync docs同步问题

### ISSUE THREAD

**Issue by thinkasany** [xiaoxunyao/cn.vitest.dev#435]
好像因为这边没做处理，所以后续的pr还是携带了那几个冲突。
<img width="1187" alt="image" src="https://github.com/vitest-dev/docs-cn/assets/117748716/0c003e71-9fa2-4de2-bcf2-57123a328c62">

**Comment by elonehoo** [comment]
我能说：“俺也不会啊，俺明天研究一下”

**Comment by thinkasany** [comment]
好像又自己好了，#436中没有遇到#435中遇到过一次，可能仅仅是和上一次diff，那暂时先不用看辣，看看后面还有没有出现了
