### ISSUE TITLE
有一些同学也想加入

### ISSUE THREAD

**Issue by elonehoo** [xiaoxunyao/cn.vitest.dev#75]
@antfu 有些同学也想来维护该文档！

起因：最近我工作了，还没有完全从学校生活适应到工作生活，所以文档一直拖沓了。

结果：有部分同学也想跟我一起维护。

想加入的同学：
- @watonyweng [Wang Weitao](https://github.com/watonyweng)

**Comment by antfu** [comment]
你应该有权限邀请维护者，可以自行判断邀请。

工作顺利！

**Comment by elonehoo** [comment]
啊，我还有这个权限啊

**Comment by elonehoo** [comment]
对不起对不起
